### ISSUE TITLE
Feature request: Allow passing in index into account_create RPC command

### ISSUE THREAD

**Issue by nullbio** [appditto/pippin_nano_wallet#10]
Slight reference to this issue: https://github.com/appditto/pippin_nano_wallet/issues/9

General gist of the idea is that it'd be useful to be able to store the addresses deterministic index in a user database alongside the address, so that disaster recovery events have an easy way to restore only the addresses you care about instead of having to generate until you find all addresses in your database. This is why it would be useful to be able to pass through the `index` into the `account_create` RPC command.

**Comment by bbedward** [comment]
Solved in the unreleased v3 rewrite
