### ISSUE TITLE
Server not listening (no error messages)

### ISSUE THREAD

**Issue by pawapps** [appditto/pippin_nano_wallet#19]
Strange issue here that I haven't been able to troubleshoot. Started today (no issues yesterday) and has occurred across three different pippin-server instances (three separate systems).

On startup, pippin-server states that it is listening on 127.0.0.1:11338

`sudo netstat -tulpn | grep LISTEN`

No listening port.

I can set up my own listen on 11338 using `nc` and I get no conflicts.

I had one server where pippin-server was still listening and to troubleshoot I restarted the service and now it won't come up and listen again. No error messages in the logs. All looks fine, just no listen.

I'm not sure how this could happen across three unique instances with no software updates. I did a complete uninstall and reinstall as well as starting up a fresh VM and installing (Ubuntu 18 server (VPS), 20 server (local VM), 20 desktop (local RPI)).

Wish I could give more information, but I guess really looking to see if others are having similar symptoms.

**Comment by adrianegraphene** [comment]
If you have [DPoW ](https://github.com/guilhermelawless/nano-dpow/tree/master/service)integrated, that service also went down today. Just FYI.

I am also dealing with issues related to outages, mostly in providing and receiving work. I cannot directly comment on how DPoW may or may not affect pippin, but I wanted to chime in to let you know you're not alone in suffering issues :)

**Comment by pawapps** [comment]
@adrianegraphene  thanks, one of my pippin-server instances was connected to DPoW and I did see the error message. I removed the DPoW .env entry and pippin-server came back up for that instance. Doesn't explain the other non-DPoW instances, though. I'll keep looking :-)

**Comment by bbedward** [comment]
Solved by #20
