### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by cbrunnkvist** [appditto/pippin_nano_wallet#39]
It looks on the surface as if this project has been languishing since 2022. It would be nice to see some kind of update - is it still being actively developed _and/or_ maintained in some other repo? Or is it done, final, and already "in production" somewhere since the last release?

**Comment by dylan1951** [comment]
Yeah also should I be using the python or go version in production?

**Comment by bbedward** [comment]
The GO version is recommended, I don’t have time to review the pending PR since I’m on a big project atm. There’s nothing really changed with the protocol that needs urgent addressing, it’s just an api wallet
