### ISSUE TITLE
Callback for new confirmed blocks for wallet accounts

### ISSUE THREAD

**Issue by guilhermelawless** [appditto/pippin_nano_wallet#4]
This is slightly related to #3 . One of the use-cases for this wallet is integrations. It would be useful if the wallet could have a callback (or websocket connection) to let users know of newly confirmed blocks for their wallet accounts.

Currently, the alternative is to setup a connection to the node websocket and specify the accounts manually.

**Comment by dylan1951** [comment]
Why is this closed? This would be great.
