### ISSUE TITLE
Difference between opengl and nocl

### ISSUE THREAD

**Issue by EmirLogas** [appditto/pippin_nano_wallet#48]
What is the difference between opengl and nocl?
![image](https://github.com/appditto/pippin_nano_wallet/assets/76751818/64651d36-e83a-43a1-8291-4e08490ab86c)

**Comment by dylan1951** [comment]
The OpenCL build uses your GPU to do the proof-of-work required to make nano transactions. You can only use it if you have a compatible GPU and the necessary drivers and runtime installed (it works great on an M1 Mac).

Otherwise use the `nocl` build.

**Comment by EmirLogas** [comment]
Thanks for informations.
