### ISSUE TITLE
Pippin not syncing wallet?

### ISSUE THREAD

**Issue by d-grasshopper** [appditto/pippin_nano_wallet#49]
Hello,

I'm trying to start working with Pippin for a NANO node. Both are running in Docker containers, Pippin has connected to the NANO node. I have created a wallet, providing a seed, but unable to see correct balance ("account_balance" and "wallet_info" both return 0). I know for a fact that wallet and account index 0 have funds.

Any tips would be appreciated, cheers!

**Comment by bbedward** [comment]
Is your nano node in sync?

**Comment by d-grasshopper** [comment]
Great question, and I don't know why I though it's synced, because it looks like it is not! Apologies, I will close this ticket now.
