### ISSUE TITLE
account_balance RPC

### ISSUE THREAD

**Issue by mikerow** [appditto/pippin_nano_wallet#6]
Is possible to get an account balance?

**Comment by bbedward** [comment]
Yes, you can post account_balance to Pippin just like you would to a node

**Comment by mikerow** [comment]
Thank you, I asked because I didn't see the command listed in the "Supported" list.
By the way, I like the tool and I hope it will become a standard for developers which don't want to rely on a full node. A light wallet for developers was I missing link that I was going to develop in PHP before I met this tool. Good work mates
