### ISSUE TITLE
Possibility to use nanovault-server instead RPC

### ISSUE THREAD

**Issue by mikerow** [appditto/pippin_nano_wallet#7]
Hi, I suggest this feature: possibility to connect to a nanovault-server (https://github.com/cronoh/nanovault-server) APIs, for example the ones hosted by MyNanoNinja and NanoCrawler for those who can't/don't want to run a own node.

**Comment by bbedward** [comment]
You can connect to public nodes like nanovault already.

Just set the node URL to https://nanovault.io/api/node-api or whichever service you want to connect to.

**Comment by mikerow** [comment]
Well, thank you for your efforts. Good tool!
