### ISSUE TITLE
pippin-server fails to start as service on system boot

### ISSUE THREAD

**Issue by pawapps** [appditto/pippin_nano_wallet#8]
**Problem**: `pippin-server` fails to start as service on system boot (`sudo systemctl status pippin`).
**Workaround**: manually start the pippin service after boot (`sudo systemctl start pippin`)

From the logs below, I think the problem is that the Nano node (on the same box) has not fully started by the time pippin-server attempts to communicate.  So when it fails to communicate, pippin-server errors out.

> -- Reboot --
> May 17 19:05:44 SomeNanoNode systemd[1]: Started Pippin Wallet.
> May 17 19:05:52 SomeNanoNode pippin-server[906]: INFO:aiohttp.server:Initializing database
> May 17 19:05:52 SomeNanoNode pippin-server[906]: INFO:root:Using SQLite database pippin.db
> May 17 19:05:52 SomeNanoNode pippin-server[906]: INFO:tortoise:Tortoise-ORM startup
> May 17 19:05:52 SomeNanoNode pippin-server[906]:     connections: {'default': {'engine': 'tortoise.backends.sqlite', 'credentials': {'journal_mode': 'WAL', 'journal_size_limit': 16384, 'file_path': '/home/jason/PippinData/pipp
> May 17 19:05:52 SomeNanoNode pippin-server[906]:     apps: {'db': {'models': ['pippin.db.models.wallet', 'pippin.db.models.account', 'pippin.db.models.adhoc_account', 'pippin.db.models.block'], 'default_connection': 'default'}
> May 17 19:05:52 SomeNanoNode pippin-server[906]: ERROR:aiohttp.server:Couldn't do is_alive RPC call
> May 17 19:05:52 SomeNanoNode pippin-server[906]: Traceback (most recent call last):
> May 17 19:05:52 SomeNanoNode pippin-server[906]:   File "/home/jason/.local/lib/python3.7/site-packages/aiohttp/connector.py", line 936, in _wrap_create_connection
> May 17 19:05:52 SomeNanoNode pippin-server[906]:     return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
> May 17 19:05:52 SomeNanoNode pippin-server[906]:   File "uvloop/loop.pyx", line 1974, in create_connection
> May 17 19:05:52 SomeNanoNode pippin-server[906]:   File "uvloop/loop.pyx", line 1951, in uvloop.loop.Loop.create_connection
> May 17 19:05:52 SomeNanoNode pippin-server[906]: ConnectionRefusedError: [Errno 111] Connection refused
> May 17 19:05:52 SomeNanoNode pippin-server[906]: The above exception was the direct cause of the following exception:
> May 17 19:05:52 SomeNanoNode pippin-server[906]: Traceback (most recent call last):
> May 17 19:05:52 SomeNanoNode pippin-server[906]:   File "/home/jason/.local/lib/python3.7/site-packages/pippin/main.py", line 78, in main
> May 17 19:05:52 SomeNanoNode pippin-server[906]:     is_alive = loop.run_until_complete(RPCClient.instance().is_alive())
> May 17 19:05:52 SomeNanoNode pippin-server[906]:   File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
> May 17 19:05:52 SomeNanoNode pippin-server[906]:   File "/home/jason/.local/lib/python3.7/site-packages/pippin/network/rpc_client.py", line 134, in is_alive
> May 17 19:05:52 SomeNanoNode pippin-server[906]:     respjson = await self.make_request(test_action)
> May 17 19:05:52 SomeNanoNode pippin-server[906]:   File "/home/jason/.local/lib/python3.7/site-packages/pippin/network/rpc_client.py", line 31, in make_request
> May 17 19:05:52 SomeNanoNode pippin-server[906]:     async with self.session.post(self.node_url ,json=req_json, timeout=300) as resp:
> May 17 19:05:52 SomeNanoNode pippin-server[906]:   File "/home/jason/.local/lib/python3.7/site-packages/aiohttp/client.py", line 1012, in __aenter__
> May 17 19:05:52 SomeNanoNode pippin-server[906]:     self._resp = await self._coro
> May 17 19:05:52 SomeNanoNode pippin-server[906]:   File "/home/jason/.local/lib/python3.7/site-packages/aiohttp/client.py", line 483, in _request
> May 17 19:05:52 SomeNanoNode pippin-server[906]:     timeout=real_timeout
> May 17 19:05:52 SomeNanoNode pippin-server[906]:   File "/home/jason/.local/lib/python3.7/site-packages/aiohttp/connector.py", line 523, in connect
> May 17 19:05:52 SomeNanoNode pippin-server[906]:     proto = await self._create_connection(req, traces, timeout)
> May 17 19:05:52 SomeNanoNode pippin-server[906]:   File "/home/jason/.local/lib/python3.7/site-packages/aiohttp/connector.py", line 859, in _create_connection
> May 17 19:05:52 SomeNanoNode pippin-server[906]:     req, traces, timeout)
> May 17 19:05:52 SomeNanoNode pippin-server[906]:   File "/home/jason/.local/lib/python3.7/site-packages/aiohttp/connector.py", line 1004, in _create_direct_connection
> May 17 19:05:52 SomeNanoNode pippin-server[906]:     raise last_exc
> May 17 19:05:52 SomeNanoNode pippin-server[906]:   File "/home/jason/.local/lib/python3.7/site-packages/aiohttp/connector.py", line 986, in _create_direct_connection
> May 17 19:05:52 SomeNanoNode pippin-server[906]:     req=req, client_error=client_error)
> May 17 19:05:52 SomeNanoNode pippin-server[906]:   File "/home/jason/.local/lib/python3.7/site-packages/aiohttp/connector.py", line 943, in _wrap_create_connection
> May 17 19:05:52 SomeNanoNode pippin-server[906]:     raise client_error(req.connection_key, exc) from exc
> May 17 19:05:52 SomeNanoNode pippin-server[906]: aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 127.0.0.1:7076 ssl:default [Connection refused]
> May 17 19:05:52 SomeNanoNode pippin-server[906]: ERROR:aiohttp.server:Error: Could not connect to remote node at http://127.0.0.1:7076
> May 17 19:05:52 SomeNanoNode pippin-server[906]: INFO:aiohttp.server:Pipping is exiting
> May 17 19:05:52 SomeNanoNode pippin-server[906]: INFO:tortoise:Tortoise-ORM shutdown
> May 17 19:05:52 SomeNanoNode pippin-server[906]: ERROR:asyncio:Task exception was never retrieved
> May 17 19:05:52 SomeNanoNode pippin-server[906]: future: <Task finished coro=<PippinServer.stop() done, defined at /home/jason/.local/lib/python3.7/site-packages/pippin/server/pippin_server.py:37> exception=RuntimeError('Canno
> May 17 19:05:52 SomeNanoNode pippin-server[906]: Traceback (most recent call last):
> May 17 19:05:52 SomeNanoNode pippin-server[906]:   File "/home/jason/.local/lib/python3.7/site-packages/pippin/server/pippin_server.py", line 38, in stop
> May 17 19:05:52 SomeNanoNode pippin-server[906]:     await self.app.shutdown()
> May 17 19:05:52 SomeNanoNode pippin-server[906]:   File "/home/jason/.local/lib/python3.7/site-packages/aiohttp/web_app.py", line 396, in shutdown
> May 17 19:05:52 SomeNanoNode pippin-server[906]:     await self.on_shutdown.send(self)
> May 17 19:05:52 SomeNanoNode pippin-server[906]:   File "/home/jason/.local/lib/python3.7/site-packages/aiohttp/signals.py", line 31, in send
> May 17 19:05:52 SomeNanoNode pippin-server[906]:     raise RuntimeError("Cannot send non-frozen signal.")
> May 17 19:05:52 SomeNanoNode pippin-server[906]: RuntimeError: Cannot send non-frozen signal.

**Comment by bbedward** [comment]
What does your systemd file look like

**Comment by pawapps** [comment]
> [Unit]
> Description=Pippin Wallet
> After=network.target
> 
> [Service]
> Type=simple
> User=jason
> Group=jason
> ExecStart=/home/jason/.local/bin/pippin-server
> 
> [Install]
> WantedBy=multi-user.target

**Comment by bbedward** [comment]
I would add Restart=on-failure or Restart=always to the service block

**Comment by pawapps** [comment]
Learn something new every day, thanks!
