### ISSUE TITLE
"Node wallet" is not recommend for production use?

### ISSUE THREAD

**Issue by nullbio** [appditto/pippin_nano_wallet#9]
From your docs:

> The Nano developer wallet (aka "node wallet") is not recommended for production use. One of the goals of Pippin is to provide a production-ready external key management that can be used by developers who are using Nano.

Are you saying that the official Nano node is not recommended for production use, or am I reading this wrong? If so, why is that the case? Thanks.

**Comment by bbedward** [comment]
Not the node, the wallet that's built into the node

From the nano docs: https://docs.nano.org/commands/rpc-protocol/#wallet-rpcs

```
For development and testing only

Below are RPC commands that interact with the built-in, QT-based node wallet. This wallet is only recommended for development and testing. For production integrations, setting up custom External Management processes is required.
```

They recommend external key management, which is something Pippin provides.

**Comment by bbedward** [comment]
For all integrations, using the `id` parameter is recommended for RPC "send", something important to note. That is a unique identifier your application should use to identify a transaction.

**Comment by nullbio** [comment]
Okay, thanks. We were going to use the index with `account_create` to associate addresses to users, and in the event of data recover we'd have a way to restore all accounts that way without missing any or overshooting generation beyond what is needed, but your docs mention that one of the key differences is that Pippin doesn't take an index for `account_create`. Is there some alternative way to do this with Pippin? Perhaps our data recovery idea has faults? Curious to know why you removed that index. Thanks for the help.

**Comment by bbedward** [comment]
It's not like that in Pippin just due to how the process is implemented, it could be re-worked to allow that but is a little different due to Pippins usage of a relational database instead of a nosql one.

Index is generated sequentially for a seed so when you call `account_create` it'll return account 0, 1 ,2, etc. every time you make the call it'll create the next one in order.

If you want to restore accounts, all you need is the number of accounts. So if there's 500 accounts you need to restore you can do

```
{
    "action":"accounts_create",
    "wallet":"some-uuid",
     "count":500
}
```

I'd recommend associating them to users by the address rather than index, since you need the address to make all of the other RPC calls anyway.

Just backup the seed (note that wallet ID is NOT the seed), the user/address relationships and that should be all you need to restore you app in the event of failure.

**Comment by nullbio** [comment]
I did consider using the number of registered users as a metric to determine how many accounts to regenerate, or perhaps a tally stored somewhere in the database every time a new account is created. The idea of it scares me a little bit though because if for example (and not saying that this should or would happen, but it's a possibility that I don't like) someone was to manually go on the server and create a bunch of accounts in-between other webservice-created accounts, now I can no longer rely on that tally to correctly regenerate state. if I had a count of 500 and regenerated 500 addresses, but someone manually created 10 accounts in-between that 500 somewhere, now my count is wrong and 10 users are probably missing fund associations and we'd have to painstakingly  try and figure out what that gap is.

There's an RPC call to list all accounts though, so I suppose you could always just keep regenerating until your database addresses list versus RPC accounts list diff is a match, but it's a rather inefficient process by the sounds of it - hence why we thought storing the address AND the index on the user would be a good way to cover all scenarios in an efficient manner, whilst having certainty that you've regenerated all addresses. (was always planning on storing address against the user as well).

Anyway, some food for thought if you ever wanted to consider adding the index. There's always some work-arounds by the sounds of things - I personally think they're a little suboptimal which is unfortunate, but some way is better than no way. Appreciate you sharing your wisdom with me.

**Comment by bbedward** [comment]
You could create a second issue for implementing the index to track progress on it. It's not a purposeful that it's not supported, Pippin just doesn't support every* feature the node wallet does yet. It just supports most of them currently

Although, I would recommend not using the wallet outside of the app. I mean the case of generating accounts outside of the app isn't ideal. But I understand the concern.
